version: '3'
services:
  write-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  read-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE="vf-read-db"
  event-store:
    image: mongo:6.0.4
    ports:
      - 27018:27017
    environment:
      - MONGODB_DATABASE="vf-event-store"
    command: mongod --replSet vf-event-store-repl-store
    volumes:
      - ./scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/event-storeinit.js:ro
